[package]
name = "macros"
version = "0.1.0"
authors = ["Peter Keay <pete@obi.money>"]
edition = "2018"

[features]
default = ["secretwasm"]
cosmwasm = ["cosmwasm-std"]
secretwasm = ["secret-cosmwasm-std"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { version = "1.1.6", optional = true, features = ["staking"] }
secret-cosmwasm-std = { version = "1.1.11", optional = true, features = ["staking"] }
