[package]
name = "classes"
version = "0.1.0"
authors = ["Peter Keay <pete@obi.money>"]
edition = "2018"

[features]
default = ["secretwasm"]
cosmwasm = ["osmosis-std", "cw20", "cosmwasm-std", "cw-storage-plus"]
secretwasm = ["osmosis-std", "secret-cosmwasm-std", "secret-toolkit", "secret-macros"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
common = { path = "../common" }
macros = { path = "../macros" }
secret-macros = { path = "../secret_macros", optional = true }
uniserde = { path = "../uniserde" }

cosmwasm-schema = "1.2.5"
cosmwasm-std = { version = "1.1.6", optional = true, features = ["staking"] }
cw-storage-plus = { version = "1.0.1", optional = true}
cw20 = { version = "1.0.1", optional = true }
secret-cosmwasm-std = { version = "1.1.11", optional = true, features = ["staking"] }
secret-toolkit = { version = "0.10.0", optional = true, default-features = false, features = ["utils", "storage", "serialization"] }
osmosis-std = { version = "0.15.3", optional = true }

base64 = "0.21.4"
hex = "0.4.3"
num-integer = { version = "0.1.36", default-features = false }
num-traits = { version = "0.2", default-features = false }
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
schemars = "0.8.3"
thiserror = { version = "1.0.21" }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }

[dev-dependencies]
